countries = ['China','America','England','Russia','Franch']
print(countries)
print(sorted(countries))
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)